update dynamic

diff --git a/dynamic/Allrun b/dynamic/Allrun
--- a/dynamic/Allrun
+++ b/dynamic/Allrun
@@ -2,27 +2,91 @@
 cd ${0%/*} || exit 1    # Run from this directory
 . $WM_PROJECT_DIR/bin/tools/RunFunctions
 
-./Allrun.pre
-rm ./0/pointDisplacement
-cp ./0.orig/pointDisplacement ./0/
 
-# Cleanup old junk that may prevent things from starting
-\rm -f comms/OpenFOAM.lock
-\rm -f ../fem/break.foam
+# 1) First run steady-state to establish a good initial field.
+# 2) Copy the latest state-state results for the transient case,
+#    but need to copy the pointDisplacement from the 0/ directory
+#    since it will not have been used for the steady-state case
+# 3) Relocate this initial solution to coincide with the first deltaT
+#    to avoid overwriting the 0/ directory at all.
 
-mkdir comms
+#
+# copyParallelPointDisplacement caseDir timeName
+#
+# Copy pointDisplacement from caseDir/0/ to caseDir/timeName/
+#
+copyParallelPointDisplacement()
+{
+    local src=$1
+    local dstTime=$2
+    local file=pointDisplacement
 
-# If OpenFOAM stops prematurely, trigger the external solver to stop
-trap '[ -e comms/OpenFOAM.lock ] && echo "status=done" > comms/OpenFOAM.lock' EXIT TERM INT
+    [ -d "$src" ] || {
+        echo "Error: no directory: $src"
+        return 1
+    }
 
-# Simulated external solver.
-# Using -scale since the input movement table is excessively large
-#runApplication -overwrite \
-#    lumpedPointMovement -scale 0.0001 -removeLock -slave ../files/response.txt &
-#../fem/write_input2.py &
-../fem/write_input_exp.py &
+    # Copy select directories
+    echo "    copy processor '$file' from 0/ -> $dstTime"
+    if [ -n "$dstTime" ]
+    then
+    (
+        cd $src || exit 1
 
-runApplication $(getApplication)
+        for proc in processor*
+        do
+            [ -d "$proc/0" -a -d "$proc/$dstTime" ] && \
+                cp $proc/0/$file $proc/$dstTime/$file
+        done
+    )
+    else
+        echo "    no destination time"
+    fi
 
-touch ./../fem/break.foam
+    # Restart from latestTime
+    foamDictionary $src/system/controlDict \
+        -entry startFrom -set latestTime
+
+    deltaT=$(foamDictionary $src/system/controlDict -entry deltaT -value)
+    latestTime=$(foamListTimes -case $src -noZero -latestTime)
+
+    # Restart using steady results as first deltaT interval
+    echo "deltaT=$deltaT latestTime=$latestTime"
+    if [ -n "$latestTime" -a "$deltaT" != "$latestTime" ]
+    then
+    (
+        cd $src || exit 1
+
+        for proc in processor*
+        do
+            if [ -d "$proc/$latestTime" -a ! -d "$proc/$deltaT" ]
+            then
+                mv $proc/$latestTime $proc/$deltaT
+                \rm -rf $proc/$deltaT/uniform
+            fi
+        done
+    )
+    fi
+
+    return 0
+}
+
+
+# Do steady-state case
+(cd steady && foamRunTutorials)
+
+if ! isTest $@
+then
+    latestTime=$(cd steady && foamListTimes -noZero -latestTime)
+
+    # Clone the steady-state case to transient
+    # cloneParallelCase steady transient 0 $latestTime
+    cp -r steady/0 transient
+
+    #copyParallelPointDisplacement transient $latestTime
+
+    # Do the transient case
+    (cd transient && foamRunTutorials)
+fi
+
 #------------------------------------------------------------------------------
